spring.application.name=hospitapi-notification
server.port=8081
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:hospitapi}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:hospitapi}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=2
spring.rabbitmq.listener.simple.retry.initial-interval=1s
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=10s